### PR TITLE
Removed 'Add task' button outline.

### PR DESCRIPTION
**Pull request by JohnBakhmat**
# This fucking black outline around buttons drives me crazy. I removed it 🤣

### CODE REVIEW

**Comment by Lumineks** [comment]
Black outline is visible when we press tab button, so we can see current element. Just removing it disables keyboard visible interaction, so i suggest to style it in a better way instead of hiding - any ideas?

**Comment by JohnBakhmat** [comment]
There is a ring "thing" in TailwindCss but im not sure how to convert it to css.
[LINK](https://tailwindcss.com/docs/ring-width) @Lumineks

**Review by Lumineks — COMMENTED** [review]
Change focus styles to this box-shadow: box-shadow: 0 0 0 3px rgba(16, 185, 129, 0.5);

**Review by Lumineks — COMMENTED** [review]
And this shadow here: box-shadow: 0 0 0 3px rgba(252, 165, 165, 0.5);

**Comment by JohnBakhmat** [comment]
@Lumineks чекни вот такой вариант

**Comment by Lumineks** [comment]
@Yevhenii-Bakhmat скейл при фокусе вообще не смотрится как мне кажется, а вот белая обводка дополнительно хорошо зашла, чекни ласт пуш

**Comment by JohnBakhmat** [comment]
@Lumineks Во да крутяк

**Pull request closed without merging**
